# 新增 playbooks/control.yml
- name: 管理服务
  hosts: "{{ target | default('mev_servers') }}"
  vars:
    action: "{{ start|default('restart') }}"
  
  tasks:
    - name: 重启服务
      shell: |
        screen -S auto-bot -X stuff "^C"  # 发送Ctrl-C
        screen -S auto-bot -X stuff "./run.sh\n"
      when: action == 'restart'

    - name: 停止服务
      shell: screen -S auto-bot -X quit
      when: action == 'stop'

    - name: 查看状态
      shell: screen -ls | grep auto-bot
      register: status
      changed_when: false

    - debug:
        msg: "服务运行状态：{{ status.stdout }}"
