- name: Deploy MEV Bot
  hosts: mev_servers
  become: yes
  vars:
    app_dir: /root/auto-bot
    encrypted_key: "{{ playbook_dir }}/privatekey/PRIVATEKEY"

  tasks:
    # 创建运行目录
    - name: create bot dir
      file:
        path: /root/auto-bot
        state: directory

    # 安装依赖
    - name: install OS module
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - unzip
        - tmux
        - iputils-ping
        - net-tools

    # 下载发布版本
    - name: download rust-mev-bot.zip
      become_user: root
      shell:
        cmd: "wget -q -O /root/auto-bot/rust-mev-bot.zip https://sourceforge.net/projects/rust-mev-bot/files/rust-mev-bot-1.0.17.zip"
        chdir: /root/auto-bot
        creates: /root/auto-bot/rust-mev-bot.zip # 避免重复下载

    # 解压文件
    - name: unzip rust-mev-bot.zip
      unarchive:
        src: /root/auto-bot/rust-mev-bot.zip
        dest: /root/auto-bot
        remote_src: yes
        owner: root
        group: root

    # 生成配置文件
    - name: generate config.yaml
      template:
        src: config.yaml.j2
        dest: /root/auto-bot/config.yaml
        owner: root
        group: root
        mode: 0644

      # 安全传输加密私钥（新增任务）
    - name: copy encrypted private key
      copy:
        src: "{{ encrypted_key }}"
        dest: "{{ app_dir }}/PRIVATEKEY"
        owner: root
        group: root
        mode: 0600
      no_log: true # 禁止输出传输日志

    # 设置执行权限
    - name: chmod sh 0755
      file:
        path: "{{ item }}"
        mode: 0755
      loop:
        - /root/auto-bot/run.sh
        - /root/auto-bot/upgrade.sh

    # 更新版本
    - name: upgrade sh
      shell:
        cmd: ./upgrade.sh
        chdir: /root/auto-bot

    # 清理旧会话
    - name: clear auto-bot tmux
      shell: |
        tmux ls | grep auto-bot | cut -d: -f1 | xargs -r -I {} tmux kill-session -t {}
      args:
        executable: /bin/bash
      register: kill_tmux
      become: yes
      ignore_errors: yes

    # 通过tmux启动服务
    - name: run server in tmux
      shell: |
        /usr/bin/tmux new-session -d -s auto-bot
        /usr/bin/tmux send-keys -t auto-bot "cd /root/auto-bot && ./run.sh" C-m
      args:
        executable: /bin/bash
      register: tmux_start
      changed_when: "'auto-bot' not in tmux_start.stdout"

    # 验证服务状态
    - name: -- check tmux --
      shell: tmux ls | grep auto-bot
      register: tmux_status
      changed_when: false

    - name: show tmux status
      debug:
        msg: "服务已在tmux会话 [auto-bot] 中运行"
      when: "'auto-bot' in tmux_status.stdout"
