- name: Restart MEV Bot Service
  hosts: mev_servers
  become: yes
  vars:
    app_dir: /root/auto-bot

  tasks:
    # 清理所有存在的auto-bot tmux会话
    - name: Terminate existing bot sessions
      shell: |
        tmux ls | grep auto-bot | cut -d: -f1 | xargs -r -I {} tmux kill-session -t {}
      args:
        executable: /bin/bash
      ignore_errors: yes
      register: session_cleanup

    # 确保脚本可执行
    - name: Set executable permissions for run.sh
      file:
        path: "{{ app_dir }}/run.sh"
        mode: 0755

    # 通过tmux启动新服务
    - name: Launch bot in tmux session
      shell: |
        /usr/bin/tmux new-session -d -s auto-bot
        /usr/bin/tmux send-keys -t auto-bot "cd /root/auto-bot && ./run.sh" C-m
      args:
        executable: /bin/bash

    # 服务状态验证
    - name: Verify tmux session
      shell: tmux ls | grep auto-bot
      register: session_status
      changed_when: false

    - name: Display restart status
      debug:
        msg: "✅ Bot已在tmux会话 [auto-bot] 中成功重启"
      when: "'auto-bot' in session_status.stdout"
